name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    
    - name: Setup Godot
      uses: godotengine/godot-ci@v1
      with:
        version: '4.2'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Run tests
      run: |
        godot --headless --script tests/run_tests.gd
        dotnet test
    
    - name: Build project
      run: godot --headless --export-release "Linux/X11" ./export/AoSGame.x86_64

  build-windows:
    runs-on: windows-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    
    - name: Setup Godot
      uses: godotengine/godot-ci@v1
      with:
        version: '4.2'
    
    - name: Build Windows
      run: godot --headless --export-release "Windows Desktop" ./export/AoSGame.exe
    
    - name: Upload Windows Build
      uses: actions/upload-artifact@v4
      with:
        name: AoSGame-Windows
        path: ./export/AoSGame.exe

  build-macos:
    runs-on: macos-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    
    - name: Setup Godot
      uses: godotengine/godot-ci@v1
      with:
        version: '4.2'
    
    - name: Build macOS
      run: godot --headless --export-release "macOS" ./export/AoSGame.dmg
    
    - name: Upload macOS Build
      uses: actions/upload-artifact@v4
      with:
        name: AoSGame-macOS
        path: ./export/AoSGame.dmg

  build-linux:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    
    - name: Setup Godot
      uses: godotengine/godot-ci@v1
      with:
        version: '4.2'
    
    - name: Build Linux
      run: godot --headless --export-release "Linux/X11" ./export/AoSGame.x86_64
    
    - name: Upload Linux Build
      uses: actions/upload-artifact@v4
      with:
        name: AoSGame-Linux
        path: ./export/AoSGame.x86_64

  release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-linux]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          AoSGame-Windows/AoSGame.exe
          AoSGame-macOS/AoSGame.dmg
          AoSGame-Linux/AoSGame.x86_64
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          Automated release from CI/CD pipeline
          
          Changes in this release:
          - See commit history for details
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
